services:
  - type: web
    name: gourmet-delights-api
    env: node
    nodeVersion: 18.19.0
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server/dist/server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_FbMU0ABlY4tj@ep-cold-snow-a5jnccig-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require

  - type: web
    name: gourmet-delights-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://gourmet-delights-api.onrender.com 